<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

url = 'https://github.com/huynhhoc/DataAnalystDeepLearning/raw/refs/heads/main/Data/dulieuxettuyendaihoc.csv'
df = pd.read_csv(url)
# Hiển thị 5 dòng dữ liệu đầu tiên
df.head()

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A

In [11]:
# 1. Kiểm tra kích thước bộ dữ liệu
print('Kích thước bảng dữ liệu mẫu:', df.shape, end='\n\n')

# 2. Xem thông tin chi tiết kiểu dữ liệu của các cột
# Hàm .info() sẽ liệt kê tên từng cột, số lượng cột, số lượng ô có dữ liệu và kiểu dữ liệu
print('Thông tin kiểu dữ liệu:')
df.info()
print('\n')

# Kiểm tra xem dữ liệu có bị thiếu không (trống) ở cột nào không
# Hàm .isnull() sẽ kiểm tra từng ô, kết hợp với .sum() để cộng tổng số ô trống ở từng cột
print('--- Số lượng giá trị thiếu ở mỗi cột ---')
print(df.isnull().sum(), end='\n\n')

Kích thước bảng dữ liệu mẫu: (100, 56)

Thông tin kiểu dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     100 non-null    int64
 1   T1      100 non-null    float64
 2   L1      100 non-null    float64
 3   H1      100 non-null    float64
 4   S1      100 non-null    float64
 5   V1      100 non-null    float64
 6   X1      100 non-null    float64
 7   D1      100 non-null    float64
 8   N1      100 non-null    float64
 9   T2      100 non-null    float64
 10  L2      100 non-null    float64
 11  H2      100 non-null    float64
 12  S2      100 non-null    float64
 13  V2      100 non-null    float64
 14  X2      100 non-null    float64
 15  D2      100 non-null    float64
 16  N2      100 non-null    float64
 17  T3      100 non-null    float64
 18  L3      100 non-null    float64
 19  H3      100 non-null    float64
 20  S3      100 non-null    float64
 21  V3      100 non-null    float64
 22  X3      100 non-null    float64
 23  D3      100 non-null    float64
 24  N3      100 non-null    float64
 25  T4      100 non-null    float64
 26  L4      100 non-null    float64
 27  H4      100 non-null    float64
 28  S4      100 non-null    float64
 29  V4      100 non-null    float64
 30  X4      100 non-null    float64
 31  D4      100 non-null    float64
 32  N4      100 non-null    float64
 33  T5      100 non-null    float64
 34  L5      100 non-null    float64
 35  H5      100 non-null    float64
 36  S5      100 non-null    float64
 37  V5      100 non-null    float64
 38  X5      100 non-null    float64
 39  D5      100 non-null    float64
 40  N5      100 non-null    float64
 41  T6      100 non-null    float64
 42  L6      100 non-null    float64
 43  H6      100 non-null    float64
 44  S6      100 non-null    float64
 45  V6      100 non-null    float64
 46  X6      100 non-null    float64
 47  D6      100 non-null    float64
 48  N6      100 non-null    float64
 49  GT      100 non-null    object
 50  DT      3 non-null      float64
 51  KV      100 non-null    object
 52  DH1     100 non-null    float64
 53  DH2     100 non-null    float64
 54  DH3     100 non-null    float64
 55  KT      100 non-null    object
dtypes: float64(52), int64(1), object(3)
memory usage: 43.9+ KB


--- Số lượng giá trị thiếu ở mỗi cột ---
STT     0
T1      0
L1      0
H1      0
S1      0
V1      0
X1      0
D1      0
N1      0
T2      0
L2      0
H2      0
S2      0
V2      0
X2      0
D2      0
N2      0
T3      0
L3      0
H3      0
S3      0
V3      0
X3      0
D3      0
N3      0
T4      0
L4      0
H4      0
S4      0
V4      0
X4      0
D4      0
N4      0
T5      0
L5      0
H5      0
S5      0
V5      0
X5      0
D5      0
N5      0
T6      0
L6      0
H6      0
S6      0
V6      0
X6      0
D6      0
N6      0
GT      0
DT     97
KV      0
DH1     0
DH2     0
DH3     0
KT      0
dtype: int64

## Tiền xử lý dữ liệu

In [14]:
# Xóa các cột dư thừa
df.drop(columns=['STT', 'GT', 'DT', 'KV'], axis=1, inplace=True)

# Các cột còn lại sau khi xóa
print('Các cột còn lại sau khi xóa: ', df.columns, end='\n\n')

KeyError: "['STT', 'GT', 'DT', 'KV'] not found in axis"

In [21]:
# pd.get_dummies giúp chuyển cột dạng chữ sang cột mới tương ứng dạng số chứa số 0 hoặc 1
df_sach = pd.get_dummies(df, columns=['KT'])

# In thử 5 dòng đầu bảng mới
df_sach.head()

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,D6,N6,DH1,DH2,DH3,KT_A,KT_A1,KT_B,KT_C,KT_D1
0,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.6,5.9,3.25,3.25,4.50,False,True,False,False,False
1,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.1,4.4,6.00,4.00,3.50,False,False,False,True,False
2,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,8.1,4.6,5.00,6.75,4.00,False,False,False,True,False
3,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.3,7.4,4.25,4.25,5.25,False,False,False,False,True
4,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,7.5,7.2,4.25,4.50,5.00,True,False,False,False,False

## Chia tập train, val và test